/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLAlittlecloser.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   alittlecloser/v1
// Description:
//   A Little Closer API

#import "GTLAlittlecloserConstants.h"

#import "GTLAlittlecloserWebAlittlecloserApiMessagesBlobUploadListResponse.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesCommentsAddRequest.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesCommentsAddResponse.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesCommentsDeleteResponse.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesCommentsListResponse.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesCommentsResponseMessage.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesConnectionAddRequest.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesConnectionAddResponse.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesConnectionDeleteResponse.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesConnectionListResponse.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesConnectionResponse.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesConnectionResponseMessage.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesConnectionUpdateRequest.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesConnectionUpdateResponse.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesHSLocationAddRequest.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesHSLocationAddResponse.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesHSLocationResponse.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesLatLngMessage.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesLoginRequest.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesLoginResponse.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesMediaJsonFinalResponse.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesMediaJsonMessage.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesSearchAddRequest.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesSearchAddResponse.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesSearchDeleteResponse.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesSearchMessage.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesSearchResponse.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesSingleConnectionReponseMessage.h"

#import "GTLQueryAlittlecloser.h"
#import "GTLServiceAlittlecloser.h"
