/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLAlittlecloserWebAlittlecloserApiMessagesMediaJsonMessage.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   alittlecloser/v1
// Description:
//   A Little Closer API
// Classes:
//   GTLAlittlecloserWebAlittlecloserApiMessagesMediaJsonMessage (0 custom class methods, 5 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLAlittlecloserWebAlittlecloserApiMessagesMediaJsonMessage
//

@interface GTLAlittlecloserWebAlittlecloserApiMessagesMediaJsonMessage : GTLObject
@property (copy) NSString *blobKey;
@property (copy) NSString *fileCat;
@property (copy) NSString *filetype;
@property (retain) NSNumber *height;  // longLongValue
@property (retain) NSNumber *width;  // longLongValue
@end
