/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLAlittlecloserWebAlittlecloserApiMessagesConnectionAddRequest.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   alittlecloser/v1
// Description:
//   A Little Closer API
// Classes:
//   GTLAlittlecloserWebAlittlecloserApiMessagesConnectionAddRequest (0 custom class methods, 13 custom properties)

#import "GTLAlittlecloserWebAlittlecloserApiMessagesConnectionAddRequest.h"

// ----------------------------------------------------------------------------
//
//   GTLAlittlecloserWebAlittlecloserApiMessagesConnectionAddRequest
//

@implementation GTLAlittlecloserWebAlittlecloserApiMessagesConnectionAddRequest
@dynamic apikey, latitude, longitude, media, personalizedMessage, personthingId,
         personthingName, primaryMedia, privateLocation, requestReason, summary,
         title, type;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"personalized_message", @"personalizedMessage",
      @"personthing_id", @"personthingId",
      @"personthing_name", @"personthingName",
      @"primary_media", @"primaryMedia",
      @"private_location", @"privateLocation",
      @"request_reason", @"requestReason",
      nil];
  return map;
}

@end
