/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLAlittlecloserWebAlittlecloserApiMessagesCommentsAddRequest.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   alittlecloser/v1
// Description:
//   A Little Closer API
// Classes:
//   GTLAlittlecloserWebAlittlecloserApiMessagesCommentsAddRequest (0 custom class methods, 9 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLAlittlecloserWebAlittlecloserApiMessagesCommentsAddRequest
//

// ProtoRPC message definition to represent a scores query.

@interface GTLAlittlecloserWebAlittlecloserApiMessagesCommentsAddRequest : GTLObject
@property (retain) NSNumber *apikey;  // longLongValue
@property (copy) NSString *body;
@property (copy) NSString *connectionId;
@property (copy) NSString *media;
@property (copy) NSString *personthingId;
@property (copy) NSString *postType;
@property (copy) NSString *tags;
@property (copy) NSString *title;
@property (copy) NSString *userId;
@end
