/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLAlittlecloserWebAlittlecloserApiMessagesLatLngMessage.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   alittlecloser/v1
// Description:
//   A Little Closer API
// Classes:
//   GTLAlittlecloserWebAlittlecloserApiMessagesLatLngMessage (0 custom class methods, 9 custom properties)

#import "GTLAlittlecloserWebAlittlecloserApiMessagesLatLngMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLAlittlecloserWebAlittlecloserApiMessagesLatLngMessage
//

@implementation GTLAlittlecloserWebAlittlecloserApiMessagesLatLngMessage
@dynamic blogUrl, created, identifier, latitude, locName, longitude, title,
         type, updated;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"blog_url", @"blogUrl",
      @"id", @"identifier",
      @"loc_name", @"locName",
      nil];
  return map;
}

@end
