/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLAlittlecloserWebAlittlecloserApiMessagesLatLngMessage.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   alittlecloser/v1
// Description:
//   A Little Closer API
// Classes:
//   GTLAlittlecloserWebAlittlecloserApiMessagesLatLngMessage (0 custom class methods, 9 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLAlittlecloserWebAlittlecloserApiMessagesLatLngMessage
//

// ProtoRPC message definition to represent a score that is stored.

@interface GTLAlittlecloserWebAlittlecloserApiMessagesLatLngMessage : GTLObject
@property (copy) NSString *blogUrl;
@property (retain) GTLDateTime *created;

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (retain) NSNumber *identifier;  // longLongValue

@property (retain) NSNumber *latitude;  // doubleValue
@property (copy) NSString *locName;
@property (retain) NSNumber *longitude;  // doubleValue
@property (copy) NSString *title;
@property (copy) NSString *type;
@property (retain) GTLDateTime *updated;
@end
