/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLAlittlecloserWebAlittlecloserApiMessagesSearchAddRequest.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   alittlecloser/v1
// Description:
//   A Little Closer API
// Classes:
//   GTLAlittlecloserWebAlittlecloserApiMessagesSearchAddRequest (0 custom class methods, 14 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLAlittlecloserWebAlittlecloserApiMessagesSearchAddRequest
//

// ProtoRPC message definition to represent a scores query.

@interface GTLAlittlecloserWebAlittlecloserApiMessagesSearchAddRequest : GTLObject
@property (copy) NSString *blogTitle;
@property (copy) NSString *body;
@property (retain) GTLDateTime *created;
@property (retain) NSNumber *latitude;  // doubleValue
@property (copy) NSString *locName;
@property (retain) NSNumber *longitude;  // doubleValue
@property (copy) NSString *personthingId;
@property (copy) NSString *personthingName;
@property (copy) NSString *summary;
@property (copy) NSString *tags;
@property (copy) NSString *title;
@property (copy) NSString *type;
@property (copy) NSString *userId;
@property (copy) NSString *userName;
@end
