/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLAlittlecloserWebAlittlecloserApiMessagesSearchDeleteResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   alittlecloser/v1
// Description:
//   A Little Closer API
// Classes:
//   GTLAlittlecloserWebAlittlecloserApiMessagesSearchDeleteResponse (0 custom class methods, 1 custom properties)

#import "GTLAlittlecloserWebAlittlecloserApiMessagesSearchDeleteResponse.h"

// ----------------------------------------------------------------------------
//
//   GTLAlittlecloserWebAlittlecloserApiMessagesSearchDeleteResponse
//

@implementation GTLAlittlecloserWebAlittlecloserApiMessagesSearchDeleteResponse
@dynamic message;
@end
