/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLAlittlecloserWebAlittlecloserApiMessagesCommentsAddResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   alittlecloser/v1
// Description:
//   A Little Closer API
// Classes:
//   GTLAlittlecloserWebAlittlecloserApiMessagesCommentsAddResponse (0 custom class methods, 2 custom properties)

#import "GTLAlittlecloserWebAlittlecloserApiMessagesCommentsAddResponse.h"

// ----------------------------------------------------------------------------
//
//   GTLAlittlecloserWebAlittlecloserApiMessagesCommentsAddResponse
//

@implementation GTLAlittlecloserWebAlittlecloserApiMessagesCommentsAddResponse
@dynamic commentId, message;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"comment_id"
                                forKey:@"commentId"];
  return map;
}

@end
