/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLAlittlecloserWebAlittlecloserApiMessagesConnectionUpdateResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   alittlecloser/v1
// Description:
//   A Little Closer API
// Classes:
//   GTLAlittlecloserWebAlittlecloserApiMessagesConnectionUpdateResponse (0 custom class methods, 2 custom properties)

#import "GTLAlittlecloserWebAlittlecloserApiMessagesConnectionUpdateResponse.h"

// ----------------------------------------------------------------------------
//
//   GTLAlittlecloserWebAlittlecloserApiMessagesConnectionUpdateResponse
//

@implementation GTLAlittlecloserWebAlittlecloserApiMessagesConnectionUpdateResponse
@dynamic message, updateConnectionId;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"update_connection_id"
                                forKey:@"updateConnectionId"];
  return map;
}

@end
