/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLAlittlecloserWebAlittlecloserApiMessagesLoginRequest.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   alittlecloser/v1
// Description:
//   A Little Closer API
// Classes:
//   GTLAlittlecloserWebAlittlecloserApiMessagesLoginRequest (0 custom class methods, 2 custom properties)

#import "GTLAlittlecloserWebAlittlecloserApiMessagesLoginRequest.h"

// ----------------------------------------------------------------------------
//
//   GTLAlittlecloserWebAlittlecloserApiMessagesLoginRequest
//

@implementation GTLAlittlecloserWebAlittlecloserApiMessagesLoginRequest
@dynamic password, username;
@end
