/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLAlittlecloserWebAlittlecloserApiMessagesSearchMessage.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   alittlecloser/v1
// Description:
//   A Little Closer API
// Classes:
//   GTLAlittlecloserWebAlittlecloserApiMessagesSearchMessage (0 custom class methods, 15 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLAlittlecloserWebAlittlecloserApiMessagesSearchMessage
//

// ProtoRPC message definition to represent a score that is stored.

@interface GTLAlittlecloserWebAlittlecloserApiMessagesSearchMessage : GTLObject
@property (copy) NSString *blogTitle;
@property (copy) NSString *body;
@property (copy) NSString *connectionId;
@property (retain) GTLDateTime *created;
@property (retain) NSNumber *latitude;  // doubleValue
@property (retain) NSNumber *limit;  // longLongValue
@property (copy) NSString *locName;
@property (retain) NSNumber *longitude;  // doubleValue
@property (copy) NSString *personthingName;
@property (copy) NSString *summary;
@property (copy) NSString *tags;
@property (copy) NSString *title;
@property (copy) NSString *type;
@property (retain) GTLDateTime *updated;
@property (copy) NSString *userName;
@end
