/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLAlittlecloserWebAlittlecloserApiMessagesMediaJsonMessage.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   alittlecloser/v1
// Description:
//   A Little Closer API
// Classes:
//   GTLAlittlecloserWebAlittlecloserApiMessagesMediaJsonMessage (0 custom class methods, 5 custom properties)

#import "GTLAlittlecloserWebAlittlecloserApiMessagesMediaJsonMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLAlittlecloserWebAlittlecloserApiMessagesMediaJsonMessage
//

@implementation GTLAlittlecloserWebAlittlecloserApiMessagesMediaJsonMessage
@dynamic blobKey, fileCat, filetype, height, width;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"blob_key", @"blobKey",
      @"file_cat", @"fileCat",
      nil];
  return map;
}

@end
