/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLAlittlecloserWebAlittlecloserApiMessagesConnectionResponse.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   alittlecloser/v1
// Description:
//   A Little Closer API
// Classes:
//   GTLAlittlecloserWebAlittlecloserApiMessagesConnectionResponse (0 custom class methods, 2 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLAlittlecloserWebAlittlecloserApiMessagesSingleConnectionReponseMessage;

// ----------------------------------------------------------------------------
//
//   GTLAlittlecloserWebAlittlecloserApiMessagesConnectionResponse
//

// ProtoRPC message definition to represent a list of stored scores.

@interface GTLAlittlecloserWebAlittlecloserApiMessagesConnectionResponse : GTLObject

// ProtoRPC message definition to represent a score that is stored.
@property (retain) GTLAlittlecloserWebAlittlecloserApiMessagesSingleConnectionReponseMessage *connection;

@property (copy) NSString *message;
@end
