/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLAlittlecloserWebAlittlecloserApiMessagesHSLocationAddRequest.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   alittlecloser/v1
// Description:
//   A Little Closer API
// Classes:
//   GTLAlittlecloserWebAlittlecloserApiMessagesHSLocationAddRequest (0 custom class methods, 7 custom properties)

#import "GTLAlittlecloserWebAlittlecloserApiMessagesHSLocationAddRequest.h"

// ----------------------------------------------------------------------------
//
//   GTLAlittlecloserWebAlittlecloserApiMessagesHSLocationAddRequest
//

@implementation GTLAlittlecloserWebAlittlecloserApiMessagesHSLocationAddRequest
@dynamic apikey, blogUrl, latitude, locName, longitude, title, type;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"blog_url", @"blogUrl",
      @"loc_name", @"locName",
      nil];
  return map;
}

@end
