/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLAlittlecloserWebAlittlecloserApiMessagesHSLocationResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   alittlecloser/v1
// Description:
//   A Little Closer API
// Classes:
//   GTLAlittlecloserWebAlittlecloserApiMessagesHSLocationResponse (0 custom class methods, 3 custom properties)

#import "GTLAlittlecloserWebAlittlecloserApiMessagesHSLocationResponse.h"

#import "GTLAlittlecloserWebAlittlecloserApiMessagesLatLngMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLAlittlecloserWebAlittlecloserApiMessagesHSLocationResponse
//

@implementation GTLAlittlecloserWebAlittlecloserApiMessagesHSLocationResponse
@dynamic cursor, locations, numOfResults;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"num_of_results"
                                forKey:@"numOfResults"];
  return map;
}

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLAlittlecloserWebAlittlecloserApiMessagesLatLngMessage class]
                                forKey:@"locations"];
  return map;
}

@end
