/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLAlittlecloserWebAlittlecloserApiMessagesHSLocationAddRequest.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   alittlecloser/v1
// Description:
//   A Little Closer API
// Classes:
//   GTLAlittlecloserWebAlittlecloserApiMessagesHSLocationAddRequest (0 custom class methods, 7 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLAlittlecloserWebAlittlecloserApiMessagesHSLocationAddRequest
//

// ProtoRPC message definition to represent a scores query.

@interface GTLAlittlecloserWebAlittlecloserApiMessagesHSLocationAddRequest : GTLObject
@property (retain) NSNumber *apikey;  // longLongValue
@property (copy) NSString *blogUrl;
@property (retain) NSNumber *latitude;  // doubleValue
@property (copy) NSString *locName;
@property (retain) NSNumber *longitude;  // doubleValue
@property (copy) NSString *title;
@property (copy) NSString *type;
@end
