/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLAlittlecloserWebAlittlecloserApiMessagesCommentsDeleteResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   alittlecloser/v1
// Description:
//   A Little Closer API
// Classes:
//   GTLAlittlecloserWebAlittlecloserApiMessagesCommentsDeleteResponse (0 custom class methods, 1 custom properties)

#import "GTLAlittlecloserWebAlittlecloserApiMessagesCommentsDeleteResponse.h"

// ----------------------------------------------------------------------------
//
//   GTLAlittlecloserWebAlittlecloserApiMessagesCommentsDeleteResponse
//

@implementation GTLAlittlecloserWebAlittlecloserApiMessagesCommentsDeleteResponse
@dynamic message;
@end
