/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLAlittlecloserWebAlittlecloserApiMessagesSearchMessage.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   alittlecloser/v1
// Description:
//   A Little Closer API
// Classes:
//   GTLAlittlecloserWebAlittlecloserApiMessagesSearchMessage (0 custom class methods, 15 custom properties)

#import "GTLAlittlecloserWebAlittlecloserApiMessagesSearchMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLAlittlecloserWebAlittlecloserApiMessagesSearchMessage
//

@implementation GTLAlittlecloserWebAlittlecloserApiMessagesSearchMessage
@dynamic blogTitle, body, connectionId, created, latitude, limit, locName,
         longitude, personthingName, summary, tags, title, type, updated,
         userName;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"blog_title", @"blogTitle",
      @"connection_id", @"connectionId",
      @"loc_name", @"locName",
      @"personthing_name", @"personthingName",
      @"user_name", @"userName",
      nil];
  return map;
}

@end
