/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLAlittlecloserWebAlittlecloserApiMessagesSearchAddRequest.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   alittlecloser/v1
// Description:
//   A Little Closer API
// Classes:
//   GTLAlittlecloserWebAlittlecloserApiMessagesSearchAddRequest (0 custom class methods, 14 custom properties)

#import "GTLAlittlecloserWebAlittlecloserApiMessagesSearchAddRequest.h"

// ----------------------------------------------------------------------------
//
//   GTLAlittlecloserWebAlittlecloserApiMessagesSearchAddRequest
//

@implementation GTLAlittlecloserWebAlittlecloserApiMessagesSearchAddRequest
@dynamic blogTitle, body, created, latitude, locName, longitude, personthingId,
         personthingName, summary, tags, title, type, userId, userName;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"blog_title", @"blogTitle",
      @"loc_name", @"locName",
      @"personthing_id", @"personthingId",
      @"personthing_name", @"personthingName",
      @"user_id", @"userId",
      @"user_name", @"userName",
      nil];
  return map;
}

@end
