/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLAlittlecloserWebAlittlecloserApiMessagesConnectionDeleteResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   alittlecloser/v1
// Description:
//   A Little Closer API
// Classes:
//   GTLAlittlecloserWebAlittlecloserApiMessagesConnectionDeleteResponse (0 custom class methods, 1 custom properties)

#import "GTLAlittlecloserWebAlittlecloserApiMessagesConnectionDeleteResponse.h"

// ----------------------------------------------------------------------------
//
//   GTLAlittlecloserWebAlittlecloserApiMessagesConnectionDeleteResponse
//

@implementation GTLAlittlecloserWebAlittlecloserApiMessagesConnectionDeleteResponse
@dynamic message;
@end
