/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLAlittlecloserConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   alittlecloser/v1
// Description:
//   A Little Closer API

#import "GTLAlittlecloserConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeAlittlecloserUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
