/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLAlittlecloserWebAlittlecloserApiMessagesMediaJsonFinalResponse.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   alittlecloser/v1
// Description:
//   A Little Closer API
// Classes:
//   GTLAlittlecloserWebAlittlecloserApiMessagesMediaJsonFinalResponse (0 custom class methods, 2 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLAlittlecloserWebAlittlecloserApiMessagesMediaJsonMessage;

// ----------------------------------------------------------------------------
//
//   GTLAlittlecloserWebAlittlecloserApiMessagesMediaJsonFinalResponse
//

@interface GTLAlittlecloserWebAlittlecloserApiMessagesMediaJsonFinalResponse : GTLObject
@property (copy) NSString *filename;
@property (retain) NSArray *mediaItemMessage;  // of GTLAlittlecloserWebAlittlecloserApiMessagesMediaJsonMessage
@end
