/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLAlittlecloserWebAlittlecloserApiMessagesMediaJsonFinalResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   alittlecloser/v1
// Description:
//   A Little Closer API
// Classes:
//   GTLAlittlecloserWebAlittlecloserApiMessagesMediaJsonFinalResponse (0 custom class methods, 2 custom properties)

#import "GTLAlittlecloserWebAlittlecloserApiMessagesMediaJsonFinalResponse.h"

#import "GTLAlittlecloserWebAlittlecloserApiMessagesMediaJsonMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLAlittlecloserWebAlittlecloserApiMessagesMediaJsonFinalResponse
//

@implementation GTLAlittlecloserWebAlittlecloserApiMessagesMediaJsonFinalResponse
@dynamic filename, mediaItemMessage;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"media_item_message"
                                forKey:@"mediaItemMessage"];
  return map;
}

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLAlittlecloserWebAlittlecloserApiMessagesMediaJsonMessage class]
                                forKey:@"media_item_message"];
  return map;
}

@end
