/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLAlittlecloserWebAlittlecloserApiMessagesCommentsAddRequest.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   alittlecloser/v1
// Description:
//   A Little Closer API
// Classes:
//   GTLAlittlecloserWebAlittlecloserApiMessagesCommentsAddRequest (0 custom class methods, 9 custom properties)

#import "GTLAlittlecloserWebAlittlecloserApiMessagesCommentsAddRequest.h"

// ----------------------------------------------------------------------------
//
//   GTLAlittlecloserWebAlittlecloserApiMessagesCommentsAddRequest
//

@implementation GTLAlittlecloserWebAlittlecloserApiMessagesCommentsAddRequest
@dynamic apikey, body, connectionId, media, personthingId, postType, tags,
         title, userId;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"connection_id", @"connectionId",
      @"personthing_id", @"personthingId",
      @"post_type", @"postType",
      @"user_id", @"userId",
      nil];
  return map;
}

@end
