/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLAlittlecloserWebAlittlecloserApiMessagesCommentsListResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   alittlecloser/v1
// Description:
//   A Little Closer API
// Classes:
//   GTLAlittlecloserWebAlittlecloserApiMessagesCommentsListResponse (0 custom class methods, 3 custom properties)

#import "GTLAlittlecloserWebAlittlecloserApiMessagesCommentsListResponse.h"

#import "GTLAlittlecloserWebAlittlecloserApiMessagesCommentsResponseMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLAlittlecloserWebAlittlecloserApiMessagesCommentsListResponse
//

@implementation GTLAlittlecloserWebAlittlecloserApiMessagesCommentsListResponse
@dynamic comments, cursor, numOfResults;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"num_of_results"
                                forKey:@"numOfResults"];
  return map;
}

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLAlittlecloserWebAlittlecloserApiMessagesCommentsResponseMessage class]
                                forKey:@"comments"];
  return map;
}

@end
