/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLAlittlecloserWebAlittlecloserApiMessagesConnectionListResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   alittlecloser/v1
// Description:
//   A Little Closer API
// Classes:
//   GTLAlittlecloserWebAlittlecloserApiMessagesConnectionListResponse (0 custom class methods, 3 custom properties)

#import "GTLAlittlecloserWebAlittlecloserApiMessagesConnectionListResponse.h"

#import "GTLAlittlecloserWebAlittlecloserApiMessagesConnectionResponseMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLAlittlecloserWebAlittlecloserApiMessagesConnectionListResponse
//

@implementation GTLAlittlecloserWebAlittlecloserApiMessagesConnectionListResponse
@dynamic connections, cursor, numOfResults;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"num_of_results"
                                forKey:@"numOfResults"];
  return map;
}

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLAlittlecloserWebAlittlecloserApiMessagesConnectionResponseMessage class]
                                forKey:@"connections"];
  return map;
}

@end
