/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLQueryAlittlecloser.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   alittlecloser/v1
// Description:
//   A Little Closer API
// Classes:
//   GTLQueryAlittlecloser (15 custom class methods, 27 custom properties)
//   GTLAlittlecloserCommentsListCreated (0 custom class methods, 2 custom properties)
//   GTLAlittlecloserCommentsListUpdated (0 custom class methods, 2 custom properties)
//   GTLAlittlecloserConnectionsListCreated (0 custom class methods, 2 custom properties)
//   GTLAlittlecloserConnectionsListUpdated (0 custom class methods, 2 custom properties)
//   GTLAlittlecloserSearchQueryCreated (0 custom class methods, 2 custom properties)
//   GTLAlittlecloserSearchQueryUpdated (0 custom class methods, 2 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLAlittlecloserCommentsListCreated;
@class GTLAlittlecloserCommentsListUpdated;
@class GTLAlittlecloserConnectionsListCreated;
@class GTLAlittlecloserConnectionsListUpdated;
@class GTLAlittlecloserSearchQueryCreated;
@class GTLAlittlecloserSearchQueryUpdated;
@class GTLAlittlecloserWebAlittlecloserApiMessagesCommentsAddRequest;
@class GTLAlittlecloserWebAlittlecloserApiMessagesConnectionAddRequest;
@class GTLAlittlecloserWebAlittlecloserApiMessagesConnectionUpdateRequest;
@class GTLAlittlecloserWebAlittlecloserApiMessagesHSLocationAddRequest;
@class GTLAlittlecloserWebAlittlecloserApiMessagesLoginRequest;
@class GTLAlittlecloserWebAlittlecloserApiMessagesSearchAddRequest;

@interface GTLQueryAlittlecloser : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (assign) long long apikey;
@property (copy) NSString *blogTitle;
@property (copy) NSString *body;
// "connectionId" has different types for some query methods; see the
// documentation for the right type for each query method.
@property (retain) id connectionId;
@property (assign) long long connectionStage;
@property (copy) NSString *connectionType;
// "created" has different types for some query methods; see the documentation
// for the right type for each query method.
@property (retain) id created;
@property (copy) NSString *cursor;
@property (copy) NSString *geoDistance;
@property (copy) NSString *latitude;
@property (assign) long long limit;
@property (copy) NSString *locName;
@property (copy) NSString *longitude;
@property (copy) NSString *personthingId;
@property (copy) NSString *personthingName;
@property (copy) NSString *postId;
@property (copy) NSString *q;
@property (copy) NSString *searchDocId;
@property (copy) NSString *summary;
@property (copy) NSString *tags;
@property (copy) NSString *title;
@property (copy) NSString *type;
// "updated" has different types for some query methods; see the documentation
// for the right type for each query method.
@property (retain) id updated;
@property (copy) NSString *uploadPath;
@property (copy) NSString *userId;
@property (copy) NSString *userName;

#pragma mark -
#pragma mark "blob" methods
// These create a GTLQueryAlittlecloser object.

// Method: alittlecloser.blob.getuploadurl
//  Optional:
//   uploadPath: NSString
//  Authorization scope(s):
//   kGTLAuthScopeAlittlecloserUserinfoEmail
// Fetches a GTLAlittlecloserWebAlittlecloserApiMessagesBlobUploadListResponse.
+ (id)queryForBlobGetuploadurl;

#pragma mark -
#pragma mark "comments" methods
// These create a GTLQueryAlittlecloser object.

// Method: alittlecloser.comments.add
//  Authorization scope(s):
//   kGTLAuthScopeAlittlecloserUserinfoEmail
// Fetches a GTLAlittlecloserWebAlittlecloserApiMessagesCommentsAddResponse.
+ (id)queryForCommentsAddWithObject:(GTLAlittlecloserWebAlittlecloserApiMessagesCommentsAddRequest *)object;

// Method: alittlecloser.comments.delete
//  Optional:
//   postId: NSString
//  Authorization scope(s):
//   kGTLAuthScopeAlittlecloserUserinfoEmail
// Fetches a GTLAlittlecloserWebAlittlecloserApiMessagesCommentsDeleteResponse.
+ (id)queryForCommentsDelete;

// Method: alittlecloser.comments.list
//  Optional:
//   connectionId: For this method, "connectionId" should be of type NSString.
//   created: For this method, "created" should be of type
//     GTLAlittlecloserCommentsListCreated.
//   cursor: NSString
//   limit: long long
//   personthingId: NSString
//   tags: NSString
//   title: NSString
//   updated: For this method, "updated" should be of type
//     GTLAlittlecloserCommentsListUpdated.
//   userId: NSString
//  Authorization scope(s):
//   kGTLAuthScopeAlittlecloserUserinfoEmail
// Fetches a GTLAlittlecloserWebAlittlecloserApiMessagesCommentsListResponse.
+ (id)queryForCommentsList;

#pragma mark -
#pragma mark "connection" methods
// These create a GTLQueryAlittlecloser object.

// Method: alittlecloser.connection.getdetails
//  Optional:
//   apikey: long long
//   connectionId: For this method, "connectionId" should be of type long long.
//  Authorization scope(s):
//   kGTLAuthScopeAlittlecloserUserinfoEmail
// Fetches a GTLAlittlecloserWebAlittlecloserApiMessagesConnectionResponse.
+ (id)queryForConnectionGetdetails;

#pragma mark -
#pragma mark "connections" methods
// These create a GTLQueryAlittlecloser object.

// Method: alittlecloser.connections.add
//  Authorization scope(s):
//   kGTLAuthScopeAlittlecloserUserinfoEmail
// Fetches a GTLAlittlecloserWebAlittlecloserApiMessagesConnectionAddResponse.
+ (id)queryForConnectionsAddWithObject:(GTLAlittlecloserWebAlittlecloserApiMessagesConnectionAddRequest *)object;

// Method: alittlecloser.connections.delete
//  Optional:
//   apikey: long long
//   connectionId: For this method, "connectionId" should be of type NSString.
//  Authorization scope(s):
//   kGTLAuthScopeAlittlecloserUserinfoEmail
// Fetches a GTLAlittlecloserWebAlittlecloserApiMessagesConnectionDeleteResponse.
+ (id)queryForConnectionsDelete;

// Method: alittlecloser.connections.list
//  Optional:
//   apikey: long long
//   connectionStage: long long
//   connectionType: NSString
//   created: For this method, "created" should be of type
//     GTLAlittlecloserConnectionsListCreated.
//   cursor: NSString
//   limit: long long
//   locName: NSString
//   personthingId: NSString
//   title: NSString
//   type: NSString
//   updated: For this method, "updated" should be of type
//     GTLAlittlecloserConnectionsListUpdated.
//   userName: NSString
//  Authorization scope(s):
//   kGTLAuthScopeAlittlecloserUserinfoEmail
// Fetches a GTLAlittlecloserWebAlittlecloserApiMessagesConnectionListResponse.
+ (id)queryForConnectionsList;

// Method: alittlecloser.connections.update
//  Authorization scope(s):
//   kGTLAuthScopeAlittlecloserUserinfoEmail
// Fetches a GTLAlittlecloserWebAlittlecloserApiMessagesConnectionUpdateResponse.
+ (id)queryForConnectionsUpdateWithObject:(GTLAlittlecloserWebAlittlecloserApiMessagesConnectionUpdateRequest *)object;

#pragma mark -
#pragma mark "locations" methods
// These create a GTLQueryAlittlecloser object.

// Method: alittlecloser.locations.add
//  Authorization scope(s):
//   kGTLAuthScopeAlittlecloserUserinfoEmail
// Fetches a GTLAlittlecloserWebAlittlecloserApiMessagesHSLocationAddResponse.
+ (id)queryForLocationsAddWithObject:(GTLAlittlecloserWebAlittlecloserApiMessagesHSLocationAddRequest *)object;

// Method: alittlecloser.locations.list
//  Optional:
//   apikey: long long
//   cursor: NSString
//   limit: long long
//   type: NSString
//  Authorization scope(s):
//   kGTLAuthScopeAlittlecloserUserinfoEmail
// Fetches a GTLAlittlecloserWebAlittlecloserApiMessagesHSLocationResponse.
+ (id)queryForLocationsList;

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryAlittlecloser object.

// Method: alittlecloser.login
// Exposes an API endpoint to query for an upload URL. Args: Returns:
//  Authorization scope(s):
//   kGTLAuthScopeAlittlecloserUserinfoEmail
// Fetches a GTLAlittlecloserWebAlittlecloserApiMessagesLoginResponse.
+ (id)queryForLoginWithObject:(GTLAlittlecloserWebAlittlecloserApiMessagesLoginRequest *)object;

#pragma mark -
#pragma mark "search" methods
// These create a GTLQueryAlittlecloser object.

// Method: alittlecloser.search.add
//  Authorization scope(s):
//   kGTLAuthScopeAlittlecloserUserinfoEmail
// Fetches a GTLAlittlecloserWebAlittlecloserApiMessagesSearchAddResponse.
+ (id)queryForSearchAddWithObject:(GTLAlittlecloserWebAlittlecloserApiMessagesSearchAddRequest *)object;

// Method: alittlecloser.search.delete
//  Optional:
//   searchDocId: NSString
//  Authorization scope(s):
//   kGTLAuthScopeAlittlecloserUserinfoEmail
// Fetches a GTLAlittlecloserWebAlittlecloserApiMessagesSearchDeleteResponse.
+ (id)queryForSearchDelete;

// Method: alittlecloser.search.query
//  Optional:
//   blogTitle: NSString
//   body: NSString
//   created: For this method, "created" should be of type
//     GTLAlittlecloserSearchQueryCreated.
//   cursor: NSString
//   geoDistance: NSString
//   latitude: NSString
//   limit: long long
//   locName: NSString
//   longitude: NSString
//   personthingName: NSString
//   q: NSString
//   summary: NSString
//   tags: NSString
//   title: NSString
//   type: NSString
//   updated: For this method, "updated" should be of type
//     GTLAlittlecloserSearchQueryUpdated.
//   userName: NSString
//  Authorization scope(s):
//   kGTLAuthScopeAlittlecloserUserinfoEmail
// Fetches a GTLAlittlecloserWebAlittlecloserApiMessagesSearchResponse.
+ (id)queryForSearchQuery;

@end

#pragma mark -
#pragma mark method parameter objects
// These object are used only to pass a collection of parameters to a
// method as a single item.

// ----------------------------------------------------------------------------
//
//   GTLAlittlecloserCommentsListCreated
//

// Used for 'created' parameter on 'alittlecloser.comments.list'.

@interface GTLAlittlecloserCommentsListCreated : GTLObject
@property (retain) NSNumber *milliseconds;  // longLongValue
@property (retain) NSNumber *timeZoneOffset;  // longLongValue
@end

// ----------------------------------------------------------------------------
//
//   GTLAlittlecloserCommentsListUpdated
//

// Used for 'updated' parameter on 'alittlecloser.comments.list'.

@interface GTLAlittlecloserCommentsListUpdated : GTLObject
@property (retain) NSNumber *milliseconds;  // longLongValue
@property (retain) NSNumber *timeZoneOffset;  // longLongValue
@end

// ----------------------------------------------------------------------------
//
//   GTLAlittlecloserConnectionsListCreated
//

// Used for 'created' parameter on 'alittlecloser.connections.list'.

@interface GTLAlittlecloserConnectionsListCreated : GTLObject
@property (retain) NSNumber *milliseconds;  // longLongValue
@property (retain) NSNumber *timeZoneOffset;  // longLongValue
@end

// ----------------------------------------------------------------------------
//
//   GTLAlittlecloserConnectionsListUpdated
//

// Used for 'updated' parameter on 'alittlecloser.connections.list'.

@interface GTLAlittlecloserConnectionsListUpdated : GTLObject
@property (retain) NSNumber *milliseconds;  // longLongValue
@property (retain) NSNumber *timeZoneOffset;  // longLongValue
@end

// ----------------------------------------------------------------------------
//
//   GTLAlittlecloserSearchQueryCreated
//

// Used for 'created' parameter on 'alittlecloser.search.query'.

@interface GTLAlittlecloserSearchQueryCreated : GTLObject
@property (retain) NSNumber *milliseconds;  // longLongValue
@property (retain) NSNumber *timeZoneOffset;  // longLongValue
@end

// ----------------------------------------------------------------------------
//
//   GTLAlittlecloserSearchQueryUpdated
//

// Used for 'updated' parameter on 'alittlecloser.search.query'.

@interface GTLAlittlecloserSearchQueryUpdated : GTLObject
@property (retain) NSNumber *milliseconds;  // longLongValue
@property (retain) NSNumber *timeZoneOffset;  // longLongValue
@end
