/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLQueryAlittlecloser.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   alittlecloser/v1
// Description:
//   A Little Closer API
// Classes:
//   GTLQueryAlittlecloser (15 custom class methods, 27 custom properties)
//   GTLAlittlecloserCommentsListCreated (0 custom class methods, 2 custom properties)
//   GTLAlittlecloserCommentsListUpdated (0 custom class methods, 2 custom properties)
//   GTLAlittlecloserConnectionsListCreated (0 custom class methods, 2 custom properties)
//   GTLAlittlecloserConnectionsListUpdated (0 custom class methods, 2 custom properties)
//   GTLAlittlecloserSearchQueryCreated (0 custom class methods, 2 custom properties)
//   GTLAlittlecloserSearchQueryUpdated (0 custom class methods, 2 custom properties)

#import "GTLQueryAlittlecloser.h"

#import "GTLAlittlecloserWebAlittlecloserApiMessagesBlobUploadListResponse.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesCommentsAddRequest.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesCommentsAddResponse.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesCommentsDeleteResponse.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesCommentsListResponse.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesConnectionAddRequest.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesConnectionAddResponse.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesConnectionDeleteResponse.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesConnectionListResponse.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesConnectionResponse.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesConnectionUpdateRequest.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesConnectionUpdateResponse.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesHSLocationAddRequest.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesHSLocationAddResponse.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesHSLocationResponse.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesLoginRequest.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesLoginResponse.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesSearchAddRequest.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesSearchAddResponse.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesSearchDeleteResponse.h"
#import "GTLAlittlecloserWebAlittlecloserApiMessagesSearchResponse.h"

@implementation GTLQueryAlittlecloser

@dynamic apikey, blogTitle, body, connectionId, connectionStage, connectionType,
         created, cursor, fields, geoDistance, latitude, limit, locName,
         longitude, personthingId, personthingName, postId, q, searchDocId,
         summary, tags, title, type, updated, uploadPath, userId, userName;

+ (NSDictionary *)parameterNameMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"blog_title", @"blogTitle",
      @"connection_id", @"connectionId",
      @"connection_stage", @"connectionStage",
      @"connection_type", @"connectionType",
      @"geo_distance", @"geoDistance",
      @"loc_name", @"locName",
      @"personthing_id", @"personthingId",
      @"personthing_name", @"personthingName",
      @"post_id", @"postId",
      @"search_doc_id", @"searchDocId",
      @"upload_path", @"uploadPath",
      @"user_id", @"userId",
      @"user_name", @"userName",
      nil];
  return map;
}

#pragma mark -
#pragma mark "blob" methods
// These create a GTLQueryAlittlecloser object.

+ (id)queryForBlobGetuploadurl {
  NSString *methodName = @"alittlecloser.blob.getuploadurl";
  GTLQueryAlittlecloser *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLAlittlecloserWebAlittlecloserApiMessagesBlobUploadListResponse class];
  return query;
}

#pragma mark -
#pragma mark "comments" methods
// These create a GTLQueryAlittlecloser object.

+ (id)queryForCommentsAddWithObject:(GTLAlittlecloserWebAlittlecloserApiMessagesCommentsAddRequest *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"alittlecloser.comments.add";
  GTLQueryAlittlecloser *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLAlittlecloserWebAlittlecloserApiMessagesCommentsAddResponse class];
  return query;
}

+ (id)queryForCommentsDelete {
  NSString *methodName = @"alittlecloser.comments.delete";
  GTLQueryAlittlecloser *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLAlittlecloserWebAlittlecloserApiMessagesCommentsDeleteResponse class];
  return query;
}

+ (id)queryForCommentsList {
  NSString *methodName = @"alittlecloser.comments.list";
  GTLQueryAlittlecloser *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLAlittlecloserWebAlittlecloserApiMessagesCommentsListResponse class];
  return query;
}

#pragma mark -
#pragma mark "connection" methods
// These create a GTLQueryAlittlecloser object.

+ (id)queryForConnectionGetdetails {
  NSString *methodName = @"alittlecloser.connection.getdetails";
  GTLQueryAlittlecloser *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLAlittlecloserWebAlittlecloserApiMessagesConnectionResponse class];
  return query;
}

#pragma mark -
#pragma mark "connections" methods
// These create a GTLQueryAlittlecloser object.

+ (id)queryForConnectionsAddWithObject:(GTLAlittlecloserWebAlittlecloserApiMessagesConnectionAddRequest *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"alittlecloser.connections.add";
  GTLQueryAlittlecloser *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLAlittlecloserWebAlittlecloserApiMessagesConnectionAddResponse class];
  return query;
}

+ (id)queryForConnectionsDelete {
  NSString *methodName = @"alittlecloser.connections.delete";
  GTLQueryAlittlecloser *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLAlittlecloserWebAlittlecloserApiMessagesConnectionDeleteResponse class];
  return query;
}

+ (id)queryForConnectionsList {
  NSString *methodName = @"alittlecloser.connections.list";
  GTLQueryAlittlecloser *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLAlittlecloserWebAlittlecloserApiMessagesConnectionListResponse class];
  return query;
}

+ (id)queryForConnectionsUpdateWithObject:(GTLAlittlecloserWebAlittlecloserApiMessagesConnectionUpdateRequest *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"alittlecloser.connections.update";
  GTLQueryAlittlecloser *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLAlittlecloserWebAlittlecloserApiMessagesConnectionUpdateResponse class];
  return query;
}

#pragma mark -
#pragma mark "locations" methods
// These create a GTLQueryAlittlecloser object.

+ (id)queryForLocationsAddWithObject:(GTLAlittlecloserWebAlittlecloserApiMessagesHSLocationAddRequest *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"alittlecloser.locations.add";
  GTLQueryAlittlecloser *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLAlittlecloserWebAlittlecloserApiMessagesHSLocationAddResponse class];
  return query;
}

+ (id)queryForLocationsList {
  NSString *methodName = @"alittlecloser.locations.list";
  GTLQueryAlittlecloser *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLAlittlecloserWebAlittlecloserApiMessagesHSLocationResponse class];
  return query;
}

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryAlittlecloser object.

+ (id)queryForLoginWithObject:(GTLAlittlecloserWebAlittlecloserApiMessagesLoginRequest *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"alittlecloser.login";
  GTLQueryAlittlecloser *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLAlittlecloserWebAlittlecloserApiMessagesLoginResponse class];
  return query;
}

#pragma mark -
#pragma mark "search" methods
// These create a GTLQueryAlittlecloser object.

+ (id)queryForSearchAddWithObject:(GTLAlittlecloserWebAlittlecloserApiMessagesSearchAddRequest *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"alittlecloser.search.add";
  GTLQueryAlittlecloser *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLAlittlecloserWebAlittlecloserApiMessagesSearchAddResponse class];
  return query;
}

+ (id)queryForSearchDelete {
  NSString *methodName = @"alittlecloser.search.delete";
  GTLQueryAlittlecloser *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLAlittlecloserWebAlittlecloserApiMessagesSearchDeleteResponse class];
  return query;
}

+ (id)queryForSearchQuery {
  NSString *methodName = @"alittlecloser.search.query";
  GTLQueryAlittlecloser *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLAlittlecloserWebAlittlecloserApiMessagesSearchResponse class];
  return query;
}

@end

#pragma mark -
#pragma mark method parameter objects
// These object are used only to pass a collection of parameters to a
// method as a single item.

// ----------------------------------------------------------------------------
//
//   GTLAlittlecloserCommentsListCreated
//

@implementation GTLAlittlecloserCommentsListCreated
@dynamic milliseconds, timeZoneOffset;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"time_zone_offset"
                                forKey:@"timeZoneOffset"];
  return map;
}

@end

// ----------------------------------------------------------------------------
//
//   GTLAlittlecloserCommentsListUpdated
//

@implementation GTLAlittlecloserCommentsListUpdated
@dynamic milliseconds, timeZoneOffset;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"time_zone_offset"
                                forKey:@"timeZoneOffset"];
  return map;
}

@end

// ----------------------------------------------------------------------------
//
//   GTLAlittlecloserConnectionsListCreated
//

@implementation GTLAlittlecloserConnectionsListCreated
@dynamic milliseconds, timeZoneOffset;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"time_zone_offset"
                                forKey:@"timeZoneOffset"];
  return map;
}

@end

// ----------------------------------------------------------------------------
//
//   GTLAlittlecloserConnectionsListUpdated
//

@implementation GTLAlittlecloserConnectionsListUpdated
@dynamic milliseconds, timeZoneOffset;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"time_zone_offset"
                                forKey:@"timeZoneOffset"];
  return map;
}

@end

// ----------------------------------------------------------------------------
//
//   GTLAlittlecloserSearchQueryCreated
//

@implementation GTLAlittlecloserSearchQueryCreated
@dynamic milliseconds, timeZoneOffset;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"time_zone_offset"
                                forKey:@"timeZoneOffset"];
  return map;
}

@end

// ----------------------------------------------------------------------------
//
//   GTLAlittlecloserSearchQueryUpdated
//

@implementation GTLAlittlecloserSearchQueryUpdated
@dynamic milliseconds, timeZoneOffset;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"time_zone_offset"
                                forKey:@"timeZoneOffset"];
  return map;
}

@end
