/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLServiceAlittlecloser.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   alittlecloser/v1
// Description:
//   A Little Closer API
// Classes:
//   GTLServiceAlittlecloser (0 custom class methods, 0 custom properties)

#import "GTLAlittlecloser.h"

@implementation GTLServiceAlittlecloser

#if DEBUG
// Method compiled in debug builds just to check that all the needed support
// classes are present at link time.
+ (NSArray *)checkClasses {
  NSArray *classes = [NSArray arrayWithObjects:
                      [GTLQueryAlittlecloser class],
                      [GTLAlittlecloserWebAlittlecloserApiMessagesBlobUploadListResponse class],
                      [GTLAlittlecloserWebAlittlecloserApiMessagesCommentsAddRequest class],
                      [GTLAlittlecloserWebAlittlecloserApiMessagesCommentsAddResponse class],
                      [GTLAlittlecloserWebAlittlecloserApiMessagesCommentsDeleteResponse class],
                      [GTLAlittlecloserWebAlittlecloserApiMessagesCommentsListResponse class],
                      [GTLAlittlecloserWebAlittlecloserApiMessagesCommentsResponseMessage class],
                      [GTLAlittlecloserWebAlittlecloserApiMessagesConnectionAddRequest class],
                      [GTLAlittlecloserWebAlittlecloserApiMessagesConnectionAddResponse class],
                      [GTLAlittlecloserWebAlittlecloserApiMessagesConnectionDeleteResponse class],
                      [GTLAlittlecloserWebAlittlecloserApiMessagesConnectionListResponse class],
                      [GTLAlittlecloserWebAlittlecloserApiMessagesConnectionResponse class],
                      [GTLAlittlecloserWebAlittlecloserApiMessagesConnectionResponseMessage class],
                      [GTLAlittlecloserWebAlittlecloserApiMessagesConnectionUpdateRequest class],
                      [GTLAlittlecloserWebAlittlecloserApiMessagesConnectionUpdateResponse class],
                      [GTLAlittlecloserWebAlittlecloserApiMessagesHSLocationAddRequest class],
                      [GTLAlittlecloserWebAlittlecloserApiMessagesHSLocationAddResponse class],
                      [GTLAlittlecloserWebAlittlecloserApiMessagesHSLocationResponse class],
                      [GTLAlittlecloserWebAlittlecloserApiMessagesLatLngMessage class],
                      [GTLAlittlecloserWebAlittlecloserApiMessagesLoginRequest class],
                      [GTLAlittlecloserWebAlittlecloserApiMessagesLoginResponse class],
                      [GTLAlittlecloserWebAlittlecloserApiMessagesMediaJsonFinalResponse class],
                      [GTLAlittlecloserWebAlittlecloserApiMessagesMediaJsonMessage class],
                      [GTLAlittlecloserWebAlittlecloserApiMessagesSearchAddRequest class],
                      [GTLAlittlecloserWebAlittlecloserApiMessagesSearchAddResponse class],
                      [GTLAlittlecloserWebAlittlecloserApiMessagesSearchDeleteResponse class],
                      [GTLAlittlecloserWebAlittlecloserApiMessagesSearchMessage class],
                      [GTLAlittlecloserWebAlittlecloserApiMessagesSearchResponse class],
                      [GTLAlittlecloserWebAlittlecloserApiMessagesSingleConnectionReponseMessage class],
                      nil];
  return classes;
}
#endif  // DEBUG

- (id)init {
  self = [super init];
  if (self) {
    // Version from discovery.
    self.apiVersion = @"v1";

    // From discovery.  Where to send JSON-RPC.
    // Turn off prettyPrint for this service to save bandwidth (especially on
    // mobile). The fetcher logging will pretty print.
    self.rpcURL = [NSURL URLWithString:@"https://pivotal-essence-333.appspot.com/_ah/api/rpc?prettyPrint=false"];
  }
  return self;
}

@end
